import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
import { classifyContent, isThinking } from './classify-message';import type { CodexMessage,CodexThread,ParsedCodexHistory } from './types';
const pick=(o:any,keys:string[])=>keys.map(k=>o?.[k]).find(Boolean)
const uuidRe=/[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/i
export function resolveThreadId(raw:unknown,filePath:string){const o=raw as any;const s=pick(o,['sessionId','session_id','threadId','thread_id','conversationId','conversation_id','id']);if(typeof s==='string')return s;const m=filePath.match(uuidRe);if(m)return m[0];return crypto.createHash('sha1').update(filePath).digest('hex').slice(0,16)}
function toMessage(raw:any,file:string,idx:number,threadId:string):CodexMessage{const role=(pick(raw,['role','type','kind','name'])||'unknown').toString().toLowerCase();const text=String(pick(raw,['content','text','message','output','result','stdout','stderr'])||'').trim();if(isThinking(raw))return {id:`${threadId}-${idx}`,threadId,role:'assistant',type:'thinking-placeholder',content:'Codex 已进行思考/分析，详细过程不展示。',raw:{hidden:true}};if(raw.stdout||raw.stderr||raw.command||/terminal|shell/.test(role)){return {id:`${threadId}-${idx}`,threadId,role:'terminal',type:'terminal-output',content:[raw.stdout,raw.stderr,text].filter(Boolean).join('\n'),command:raw.command||raw.cmd,raw}}
if(role==='tool')return {id:`${threadId}-${idx}`,threadId,role:'tool',type:'tool-call',content:text||'工具调用',raw}
return {id:`${threadId}-${idx}`,threadId,role: role==='user'||role==='assistant'||role==='system'?role:'unknown',type:classifyContent(text,role) as any,content:text,createdAt:Date.parse(String(pick(raw,['timestamp','createdAt','updatedAt'])||''))||undefined,raw}}
export function parseFiles(files:string[]):ParsedCodexHistory{const by:Record<string,CodexMessage[]>={};const diagnostics:any[]=[];for(const file of files){let lines:string[]=[];try{lines=fs.readFileSync(file,'utf8').split(/\r?\n/)}catch{diagnostics.push({file,level:'error',message:'file read failed'});continue}
for(let i=0;i<lines.length;i++){if(!lines[i].trim())continue;let raw:any;try{raw=JSON.parse(lines[i])}catch{diagnostics.push({file,line:i+1,level:'warning',message:'json parse failed'});continue}const tid=resolveThreadId(raw,file);by[tid]??=[];by[tid].push(toMessage(raw,file,i,tid))}}
const threads:CodexThread[]=Object.entries(by).map(([id,msgs])=>{const firstUser=msgs.find(m=>m.role==='user'&&m.content);const firstAsst=msgs.find(m=>m.role==='assistant'&&m.content);const preview=(firstUser?.content||firstAsst?.content||'').slice(0,280);const title=(firstUser?.content||preview||'Untitled Codex Session').slice(0,60);return {id,sessionId:id,title,preview,messageCount:msgs.length,sourceFiles:[...new Set(files.filter(f=>msgs.some(m=>m.id.startsWith(id))))],primaryFile:files[0],hasThinking:msgs.some(m=>m.type==='thinking-placeholder'),hasToolCalls:msgs.some(m=>m.type==='tool-call'),hasTerminalOutput:msgs.some(m=>m.type==='terminal-output'),hasCodeChanges:msgs.some(m=>m.type==='diff'),hasErrors:msgs.some(m=>m.type==='error')}})
return {threads,messagesByThreadId:by,diagnostics}}
export function scanJsonlFiles(root:string){const out:string[]=[];const walk=(d:string)=>{for(const e of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,e.name);if(e.isDirectory())walk(p);else if(e.isFile()&&p.endsWith('.jsonl'))out.push(p)}};if(fs.existsSync(root))walk(root);return out}
